import { t } from './i18n';
import type { InstallationSectionId } from './installation-types';

export const installationFieldTemplates: Record<InstallationSectionId, [string, string][]> = {
  installation: [
    ['sv_version', '서비스 버전'],
    ['setup_year', '최초 설치 연도'],
    ['setup_date', '최초 설치일'],
    ['last_setup_date', '최종 패치일'],
    ['yeta_version', '최종 예타 유형'],
    ['setup_engineer', '최종 패치 엔지니어'],
    ['autoupdate_yn', '자동 업데이트 가능'],
    ['bonding_yn', '네트워크 본딩'],
    ['mng_cd', '설치 담당자 코드'],
    ['ct_cd', '고객사 코드'],
    ['sys_cd', '시스템 코드'],
    ['sys_member', '인원'],
    ['sys_com_count', '회사 코드 수'],
    ['ct_etc', '고객사 비고'],
    ['setup_etc', '서버 설정 비고'],
  ],
  access: [
    ['access_type', '접근 유형'],
    ['domainurl', '도메인 URL'],
    ['ssh_port', 'SSH 포트'],
    ['external_ip', '외부 IP'],
    ['internal_ip', '내부 IP'],
    ['netmask', '넷마스크'],
    ['gateway', '게이트웨이'],
    ['dns1', 'DNS 1'],
    ['dns2', 'DNS 2'],
    ['ssl_apply_yn', 'SSL 적용'],
    ['ssl_manage_type', 'SSL 관리 유형'],
    ['ssl_applydate', 'SSL 적용일'],
    ['ssl_pwd', 'SSL 비밀번호'],
    ['vpnsv_ip', 'VPN 서버 IP'],
    ['vpnsv_id', 'VPN 아이디'],
    ['vpnsv_pwd', 'VPN 비밀번호'],
    ['rootpath', '설치 경로'],
    ['os_root_id', 'OS 관리자 아이디'],
    ['os_root_pwd', 'OS 관리자 비밀번호'],
    ['os_user_id', 'OS 사용자 아이디'],
    ['os_user_pwd', 'OS 사용자 비밀번호'],
    ['os_login_etc', 'OS 로그인 비고'],
    ['access_etc', '접근 비고'],
    ['access_reqst_date', '접근 신청일'],
    ['access_reqst_enddate', '접근 종료일'],
    ['access_url', '접근 URL'],
    ['access_id', '접근 아이디'],
    ['access_pwd', '접근 비밀번호'],
  ],
  server: [
    ['hostname', '호스트네임'],
    ['servicetag', '서버 ServiceTag'],
    ['express_service_code', '서버 ExpressServiceCode'],
    ['model', '서버 모델명'],
    ['zipcode', '설치 장소 우편번호'],
    ['address', '설치 장소'],
    ['migration_date', '설치일'],
    ['migration_engineer', '엔지니어'],
  ],
  yeta: [
    ['sys_cd', '시스템 코드'],
    ['yeta_year', '연도'],
    ['ct_cd', '고객사 코드'],
    ['app_type', '구분'],
    ['comcode', '회사 코드'],
    ['yeta_id', 'YETA 아이디'],
    ['yeta_pwd', 'YETA 비밀번호'],
  ],
  sap: [
    ['sys_cd', '시스템 코드'],
    ['app_type', '구분'],
    ['app_ip', 'SAP 서버 IP'],
    ['sysnr', '인스턴스 번호'],
    ['r3name', '시스템 ID'],
    ['client', '클라이언트'],
    ['sap_id', 'SAP 아이디'],
    ['sap_pwd', 'SAP 비밀번호'],
    ['lang', '언어'],
    ['gr_id', '그룹웨어 아이디'],
    ['gr_pwd', '그룹웨어 비밀번호'],
    ['etc', '비고'],
  ],
  settings: [
    ['setting_year', '연도'],
    ['setting_type', '설정 종류'],
    ['setting_yn', '적용 여부'],
    ['setting_etc', '비고'],
  ],
  files: [
    ['system_code', '시스템 코드'],
    ['att_year', '귀속 연도'],
    ['set_name', '설정 키'],
    ['set_value', '설정 값'],
  ],
};

const builtInLabels: Record<string, string> = {
  ...Object.fromEntries(Object.values(installationFieldTemplates).flat()),
  systemCode: '시스템 코드',
  serviceVersion: '서비스 버전',
  version: '현재 버전',
  installedAt: '설치일',
  patchedAt: '최종 패치일',
  engineer: '담당 엔지니어',
  accessType: '접근 유형',
  autoUpdate: '자동 업데이트',
  domain: '도메인',
  note: '비고',
};
export function installationFieldLabel(field: { key: string; label: string }) {
  return builtInLabels[field.key] === field.label ? t(field.label) : field.label;
}
